#!/usr/bin/env bash
# Regenerate Component_Library/css from the portals' current stylesheets.
# Run from the repo root (the folder holding index.html).
set -e
D=Component_Library
cls(){ grep -oE '\.[a-zA-Z][a-zA-Z0-9_-]*' "$1" | sort -u | tr -d '.'; }

# 1 — base: the Supplier Portal's fork (the richest of the four)
cp Supplier_Portal/css/greenstreets-theme.css  $D/css/greenstreets-theme.css
cp Supplier_Portal/css/supplier-portal.css     $D/css/supplier-portal.css
cp Supplier_Portal/css/greenstreets-light.css  $D/css/greenstreets-light.css

# The editable-combo builder, so the "Editable dropdown list" specimen is driven
# by the REAL implementation instead of a static reproduction. The Retailer User
# copy is the standalone file (the Supplier Portal has the same code inline in
# supplier-portal.js). It has no auto-init — it only acts when called — so
# loading it on the catalogue page is side-effect free.
cp Retailer_User_Portal/js/gs-pkg-controls.js  $D/js/gs-pkg-controls.js
cp Supplier_Portal/js/greenstreets-theme.js    $D/js/greenstreets-theme.js
cp Supplier_Portal/js/gs-schema.js             $D/js/gs-schema.js

# 2 — the "keep" set: classes that exist in SA/RA/RU but NOT in the base
cls Supplier_Portal/css/greenstreets-theme.css   > /tmp/gsx-a
cls Supplier_Portal/css/supplier-portal.css      > /tmp/gsx-b
cls Retailer_User_Portal/css/pkg-detail.css      > /tmp/gsx-c
cat /tmp/gsx-a /tmp/gsx-b /tmp/gsx-c | sort -u   > /tmp/gsx-base
cls GreenStreets_Super_Admin/css/greenstreets-theme.css > /tmp/gsx-sa
cls Retailer_Admin_Portal/css/retailer-admin.css        > /tmp/gsx-ra
cls Retailer_User_Portal/css/retailer-user.css          > /tmp/gsx-ru
cat /tmp/gsx-sa /tmp/gsx-ra /tmp/gsx-ru | sort -u > /tmp/gsx-all
# drop bare element/keyword names that are not really component classes
comm -23 /tmp/gsx-all /tmp/gsx-base | grep -vE '^(html|style|in|bob|just-done)$' > /tmp/gsx-keep

X=$D/tools/extract-portal-extras.py
for pair in \
  "GreenStreets_Super_Admin/css/greenstreets-theme.css:/tmp/gsx-x-sa.css" \
  "Retailer_Admin_Portal/css/retailer-admin.css:/tmp/gsx-x-ra.css" \
  "Retailer_User_Portal/css/retailer-user.css:/tmp/gsx-x-ru.css" \
  "GreenStreets_Super_Admin/css/greenstreets-light.css:/tmp/gsx-l-sa.css" \
  "Retailer_Admin_Portal/css/greenstreets-light.css:/tmp/gsx-l-ra.css" \
  "Retailer_User_Portal/css/greenstreets-light.css:/tmp/gsx-l-ru.css" ; do
  python "$X" "${pair%%:*}" /tmp/gsx-keep "${pair##*:}"
done

{ echo "/* portal-extras.css — GENERATED by Component_Library/tools/regenerate.sh. Do not hand-edit."
  echo "   Rules extracted from the Super Admin / Retailer Admin / Retailer User stylesheets whose"
  echo "   every selector is anchored on a class absent from the Supplier-Portal base, so this file"
  echo "   can never restyle a shared primitive. */"
  awk '!seen[$0]++' /tmp/gsx-x-sa.css /tmp/gsx-x-ra.css /tmp/gsx-x-ru.css; } > $D/css/portal-extras.css
{ echo "/* portal-extras-light.css — GENERATED. Light-theme (body.lt) counterpart of portal-extras.css. */"
  awk '!seen[$0]++' /tmp/gsx-l-sa.css /tmp/gsx-l-ra.css /tmp/gsx-l-ru.css; } > $D/css/portal-extras-light.css

# 3 — the CSS shown beside each specimen, read back out of the copies above
python $D/tools/extract-css-index.py

# 4 — the Next.js/Tailwind code shown beside each specimen (needs step 3)
python $D/tools/build-tsx.py

# The base-only design sheet for Figma import (base-kit.html).
python $D/tools/build-base-kit.py

echo "Regenerated. Bump the ?v=N query on the <link>/<script> tags in $D/components.html."
